# Generated by Django 3.0.4 on 2020-03-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Item name')),
                ('type', models.CharField(choices=[('1', 'top'), ('2', 'bottom'), ('0', 'not select')], max_length=9)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Set name')),
                ('bottom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemSet_bottom', to='artmax.Item', verbose_name='Bottom')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemSet_top', to='artmax.Item', verbose_name='Top')),
            ],
        ),
    ]
