# Generated by Django 3.0.4 on 2020-03-05 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artmax', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='itemset',
            options={'verbose_name': 'Набор', 'verbose_name_plural': 'Наборы'},
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наменование'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('top', 'Низ'), ('bottom', 'Верх'), ('not select', 'Не выбрано')], max_length=10, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='bottom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemSet_bottom', to='artmax.Item', verbose_name='Низ'),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование набора'),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemSet_top', to='artmax.Item', verbose_name='Верх'),
        ),
    ]
