# Generated by Django 3.0.4 on 2020-03-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artmax', '0008_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itemset',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='object_id',
        ),
        migrations.AddField(
            model_name='item',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artmax.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemset',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artmax.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AllItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='artmax.Product')),
            ],
        ),
    ]
