# Generated by Django 3.0.4 on 2020-03-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artmax', '0011_auto_20200305_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producten',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='producten_ptr',
            new_name='products_ptr',
        ),
        migrations.RenameField(
            model_name='itemset',
            old_name='producten_ptr',
            new_name='products_ptr',
        ),
    ]
