# Generated by Django 3.0.4 on 2020-03-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artmax', '0013_allitem_selected_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllItem',
        ),
    ]
