# Generated by Django 3.0.4 on 2020-03-06 06:27

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artmax', '0014_delete_allitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='products_ptr',
        ),
        migrations.RemoveField(
            model_name='itemset',
            name='products_ptr',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=builtins.id, max_length=150, verbose_name='Наменование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemset',
            name='id',
            field=models.AutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemset',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='Наименование набора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemset',
            name='bottom',
            field=models.OneToOneField(limit_choices_to={'ItemSet_bottom__isnull': 'True', 'type': 'bottom'}, on_delete=django.db.models.deletion.CASCADE, related_name='ItemSet_bottom', to='artmax.Item', verbose_name='Низ'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
